"""The chronicle.

The last screen answers the first one. There is no score, no grade and no
verdict - the game reads back what was actually done, in order, and stops.

The lines arrive one at a time. Nothing here is generated by this file; it is
handed a finished chronicle by the simulation.
"""

from __future__ import annotations

import arcade

from .. import theme
from .base import FONT

LINE_DELAY = 0.42
FINAL_LINE = "This is how you lived."


class ChronicleView(arcade.View):
    def __init__(self, app, session):
        super().__init__()
        self.app = app
        self.session = session
        self.lines = session.ending()
        self.elapsed = 0.0
        self._texts: list[arcade.Text] = []
        self._footer: arcade.Text | None = None

    def on_show_view(self) -> None:
        self.window.background_color = theme.BACKDROP
        w, h = self.window.width, self.window.height

        drawable = [line for line in self.lines]
        top = h * 0.86
        self._texts = []
        for i, line in enumerate(drawable):
            final = line == FINAL_LINE
            self._texts.append(arcade.Text(
                line, w // 2, top - i * theme.SPACE_4,
                theme.with_alpha(theme.INK if final else theme.MUTED, 0),
                theme.HEADING if final else theme.BODY,
                font_name=FONT, anchor_x="center", bold=final))

        self._footer = arcade.Text(
            "Enter   live another life          Esc   quit",
            w // 2, h * 0.07, theme.with_alpha(theme.SUBTLE, 0), theme.SMALL,
            font_name=FONT, anchor_x="center")
        self.app.audio.transition()

    def on_update(self, delta_time: float) -> None:
        self.elapsed += delta_time
        for i, text in enumerate(self._texts):
            due = i * LINE_DELAY
            alpha = max(0.0, min(1.0, (self.elapsed - due) / 0.7))
            base = theme.INK if text.bold else theme.MUTED
            text.color = theme.with_alpha(base, alpha)
        if self._footer:
            done = len(self._texts) * LINE_DELAY + 1.0
            alpha = max(0.0, min(1.0, (self.elapsed - done) / 0.8))
            self._footer.color = theme.with_alpha(theme.SUBTLE, 0.86 * alpha)

    def on_draw(self) -> None:
        self.clear()
        self.window.default_camera.use()
        for text in self._texts:
            text.draw()
        if self._footer:
            self._footer.draw()

    def on_key_press(self, symbol: int, modifiers: int) -> None:
        if symbol == arcade.key.ESCAPE:
            self.window.close()
        elif symbol in (arcade.key.ENTER, arcade.key.RETURN):
            # A new life, without leaving the program. Nothing carries over.
            self.app.show_naming()

